### ISSUE TITLE
annotate fails with remote chart dependencies

### ISSUE THREAD

**Issue by ctrahey** [vmware-labs/distribution-tooling-for-helm#103]
### Describe the bug

When chart dependencies are not local, helm dependency update will download them as tarballs. For example: 

In chart.yaml
```
apiVersion: v2
name: somechart
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: redis
    version: "20.8.0"
    repository: "oci://registry-1.docker.io/bitnamicharts"
  - name: nats
    version: "1.2.9"
    repository: "https://nats-io.github.io/k8s/helm/charts/"
```
after `helm dependency update` yields this: 
```
% tree 
.
├── Chart.lock
├── Chart.yaml
├── charts
│   ├── nats-1.2.9.tgz
│   └── redis-20.8.0.tgz
├── templates
│   └── foo.yaml
└── values.yaml
```

But the command `helm dt charts annotate . ` seems to look for directories only, not tarballs:

```
failed to annotate sub-chart "somechart/charts/redis": failed to load Helm chart: stat /..snip../somechart/charts/redis: no such file or directory
failed to annotate sub-chart "somechart/charts/nats": failed to load Helm chart: stat /..snip../somechart/charts/nats: no such file or directory

```

### Reproduction steps

1. Author a chart using remove dependencies articulated in Chart.yaml
2. helm dependency update
3. helm dt charts annotate .  
4. Observe stat errors
...

### Expected behavior

Annotation should work with the default Helm behavior for dependency charts. 

### Additional context

I worked around this temporarily with `ls charts/ | xargs -n 1 tar -xzf`, but no annotations were placed in my Chart.yaml (even though the bitnami chart referenced above has image annotations; perhaps I misunderstand what annotate is for).
